feature_flags:
  - name: run_test_mode
    description: Instead of proceeding to usual kernel boot enter the test mode, which allows to run single test on the kernel.
    default: false

  - name: debug_spinlock
    description: Enables additional debug information for spinlocks, which can help to identify deadlocks and other synchronization issues.
    default: false

  - name: debug_output
    description: Enables additional terminal output directed to serial port, mostly used for qemu builds and debugging.
    default: false

  - name: debug_traces
    description: Enables additional debug traces in the kernel, which can help to identify issues during execution.
    default: false

  - name: single_trace_max_size
    description: Maximum size of a single debug trace entry in bytes.
    type: integer
    default: 2048
    min: 1
    max: 8192

  - name: trace_buffer_size
    description: Size of the trace buffer in bytes.
    type: integer
    default: 1048576
    min: 65536
    max: 8388608

  - name: memory_trace_level
    description: Level of Memory module tracing
    type: integer
    default: 2
    min: 0
    max: 3

  - name: interrupts_trace_level
    description: Level of Interrupts module tracing
    type: integer
    default: 2
    min: 0
    max: 3

  - name: boot_trace_level
    description: Level of Boot module tracing
    type: integer
    default: 2
    min: 0
    max: 3

  - name: general_trace_level
    description: Level of General module tracing
    type: integer
    default: 2
    min: 0
    max: 3

  - name: time_trace_level
    description: Level of Time module tracing
    type: integer
    default: 2
    min: 0
    max: 3
