feature_flags:
  - name: run_test_mode
    description: Instead of proceeding to usual kernel boot enter the test mode, which allows to run single test on the kernel.
    default: false

  - name: debug_spinlock
    description: Enables additional debug information for spinlocks, which can help to identify deadlocks and other synchronization issues.
    default: false

  - name: debug_output
    description: Enables additional terminal output directed to serial port, mostly used for qemu builds and debugging.
    default: false

  - name: debug_traces
    description: Enables additional debug traces in the kernel, which can help to identify issues during execution.
    default: false

  - name: relative_paths_experimental
    description: Enables relative paths in traces output. Slowdowns compilation time quite a bit, so marked as experimental.
    default: false
